# Uncomment the next line to define a global platform for your project
platform :ios, '9.3'

# ignore all warnings from all pods
inhibit_all_warnings!

# Comment the next line if you're not using Swift and don't want to use dynamic frameworks
use_frameworks!

target 'OkDataSourcesExample' do
  pod 'RxSwift', '4.2.0'
end
